'use client';

import { Role } from "./types";
import { contractAddresses } from "@/contracts/addresses";

/**
 * A centralized mapping from Role string to the on-chain numeric ID.
 * This ensures consistency across all registration and attestation flows.
 */
export const onChainRoleMap: { [key in Role]: number } = {
    // Values based on the existing map in TrustedParticipantManager.tsx
    Farmer: 1,
    Transporter: 2,
    Industry: 3,
    Government: 4,
    Admin: 5,
    Oracle: 6,
};

/**
 * EIP-712 domain separator for the Registration contract.
 * This is crucial for ensuring that the signature generated by the oracle (client-side)
 * matches the one expected by the smart contract (on-chain).
 */
export const REGISTRATION_CONTRACT_DOMAIN = {
    name: 'Registration',
    version: '1',
    chainId: 31337, // Local Anvil chain
    verifyingContract: contractAddresses.Registration as `0x${string}`,
};